-- MySQL Script generated by MySQL Workbench
-- Fri Oct 28 23:06:39 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tax
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tax
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tax` DEFAULT CHARACTER SET utf8 ;
USE `tax` ;

-- -----------------------------------------------------
-- Table `tax`.`raw_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tax`.`raw_data` ;

CREATE TABLE IF NOT EXISTS `tax`.`raw_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` LONGTEXT NULL,
  `from` VARCHAR(255) NULL,
  `ip` VARCHAR(45) NULL,
  `create_time` BIGINT(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `tax`.`cookie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tax`.`cookie` ;

CREATE TABLE IF NOT EXISTS `tax`.`cookie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `key` TEXT NULL,
  `value` TEXT NULL,
  `expires` INT NULL,
  `max_age` INT NULL,
  `domain` TEXT NULL,
  `path` TEXT NULL,
  `secure` TINYINT(1) NULL,
  `http_only` TINYINT(1) NULL,
  `creation` INT NULL,
  `last_accessed` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
