-- MySQL Script generated by MySQL Workbench
-- Wed Dec  7 00:29:24 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tax
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tax
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tax` DEFAULT CHARACTER SET utf8 ;
USE `tax` ;

-- -----------------------------------------------------
-- Table `tax`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tax`.`user` ;

CREATE TABLE IF NOT EXISTS `tax`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `mobile` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `create_time` BIGINT(20) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `mobile_UNIQUE` (`mobile` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `tax`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tax`.`company` ;

CREATE TABLE IF NOT EXISTS `tax`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `uscc` VARCHAR(45) NULL,
  `swglm` VARCHAR(45) NULL,
  `nsrsbh` VARCHAR(45) NULL,
  `create_time` BIGINT(20) NULL,
  `update_time` BIGINT(20) NULL,
  `password` VARCHAR(45) NULL,
  `last_error_code` VARCHAR(45) NULL,
  `last_error_msg` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `tax`.`company_check`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tax`.`company_check` ;

CREATE TABLE IF NOT EXISTS `tax`.`company_check` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` BIGINT(20) NULL,
  `company_id` INT NULL,
  `from` VARCHAR(45) NULL,
  `auth_info` LONGTEXT NULL,
  `fetch_info` LONGTEXT NULL,
  `result` VARCHAR(45) NULL,
  `format_text` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_company_check__company_id`
    FOREIGN KEY (`company_id`)
    REFERENCES `tax`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `tax`.`company_level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tax`.`company_level` ;

CREATE TABLE IF NOT EXISTS `tax`.`company_level` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NULL,
  `stage` VARCHAR(45) NULL,
  `d1` VARCHAR(45) NULL,
  `d2` VARCHAR(45) NULL,
  `d3` VARCHAR(45) NULL,
  `d4` VARCHAR(45) NULL,
  `d5` VARCHAR(45) NULL,
  `d6` VARCHAR(45) NULL,
  `d7` VARCHAR(45) NULL,
  `d8` VARCHAR(45) NULL,
  `d9` VARCHAR(45) NULL,
  `is_visible` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_company_level__company_id`
    FOREIGN KEY (`company_id`)
    REFERENCES `tax`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `tax`.`company_apply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tax`.`company_apply` ;

CREATE TABLE IF NOT EXISTS `tax`.`company_apply` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` BIGINT(20) NULL,
  `update_time` BIGINT(20) NULL,
  `name` VARCHAR(255) NULL,
  `uscc` VARCHAR(255) NULL,
  `gs_username` VARCHAR(255) NULL,
  `gs_password` VARCHAR(255) NULL,
  `gs_errno` VARCHAR(255) NULL,
  `gs_errmsg` VARCHAR(255) NULL,
  `ds_username` VARCHAR(255) NULL,
  `ds_password` VARCHAR(255) NULL,
  `ds_errno` VARCHAR(255) NULL,
  `ds_errmsg` VARCHAR(255) NULL,
  `content` VARCHAR(255) NULL,
  `result` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `tax`.`article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tax`.`article` ;

CREATE TABLE IF NOT EXISTS `tax`.`article` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `code` VARCHAR(45) NULL,
  `content` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `tax`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `tax`;
INSERT INTO `tax`.`user` (`id`, `username`, `mobile`, `password`, `create_time`, `email`) VALUES (1, 'admin', NULL, 'admin', NULL, NULL);

COMMIT;

